apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentatlas-staging
resources:
  - ../../base
namePrefix: ""
patches:
  - target:
      kind: Deployment
      name: agentatlas-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/topologySpreadConstraints
        value: []
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "DEBUG"
  - target:
      kind: HorizontalPodAutoscaler
      name: agentatlas-api-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
  - target:
      kind: Ingress
      name: agentatlas-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging-api.agentatlas.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging-api.agentatlas.io
images:
  - name: REGISTRY/agentatlas/api
    newTag: staging-latest
