apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentatlas
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - secrets.yaml
  - serviceaccount-ingress.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: agentatlas
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
